### PR TITLE
Get campaign size

### PR DESCRIPTION
**Pull request by eu-smirnov**

### CODE REVIEW

**Comment by lbonn** [comment]
Why is it not in metadata like the rest? You've checked with backend?

**Comment by eu-smirnov** [comment]
> Why is it not in metadata like the rest? You've checked with backend?

Ask Vladimir :) It is tested with the backend.

**Comment by patrickvacek** [comment]
@koshelev Can you confirm that this looks correct? If that is what we need, it is fine with me.

**Comment by koshelev** [comment]
@lbonn The metadata is what a user enters while creating a campaign. Size is calculated per vehicle.
@patrickvacek I can confirm it is what we need :)

**Pull request merged**
