### PR TITLE
Fix/prevent rel path misuse

### PR DESCRIPTION
**Pull request by lbonn**
And set `storage_config.sqldb_path` to be relative to `storage_config.path` by default (an absolute path is also accepted).

### CODE REVIEW

**Comment by lbonn** [comment]
I also meddled with `ImportConfig`, this will probably need re-review (last commit only)

**Comment by patrickvacek** [comment]
Just to verify: you can still use absolute paths for the import config, right? I think the assumption there was that you may get those files from a variety of sources. I don't know if it is necessary to have a base path for the import section, but if it keeps things more consistent and makes things easier, that is fine with me.

**Comment by lbonn** [comment]
Yes, it's possible to use it the same way as before: keep base_path empty and specify everything as absolute paths. Absolute paths will also work if base_path is non empty.

Maybe I should add some tests for that though.

**Comment by cajun-rat** [comment]
I'm happy.  Maybe add that test for "/base" + "/mypath" => "/mypath" and manually bitbake + boot to make sure this hasn't broken any assumptions that are in the config?

**Comment by lbonn** [comment]
Ok it passed oe-selftest

**Pull request merged**
