### PR TITLE
Move global curl initialization into static data member

### PR DESCRIPTION
**Pull request by koshelev**

### CODE REVIEW

**Comment by patrickvacek** [comment]
> I believe the old behavior was safe

Presumably @koshelev's problem is that `curl_global_init()` is not thread-safe. This never mattered for us, but it might for the load tests.

**Comment by koshelev** [comment]
@patrickvacek is right, thread-safety is what I'm trying to solve here

**Comment by cajun-rat** [comment]
I've just pushed a commit to fix the clang-format issue

**Comment by lbonn** [comment]
It should solve the thread safety problem. Relevant doc for reference: http://en.cppreference.com/w/cpp/language/storage_duration. Ok if CI.

**Pull request merged**
