### PR TITLE
Launch ptest at the end of pipelines

### PR DESCRIPTION
**Pull request by lbonn**
Will probably only enable it for master merge but it's enabled here for the test.

### CODE REVIEW

**Comment by patrickvacek** [comment]
How can I see the results of the ptest run?

**Comment by lbonn** [comment]
Before I've limited it to master and tags: https://main.gitlab.in.here.com/olp/edge/ota/connect/client/aktualizr/pipelines/49676

**Comment by lbonn** [comment]
Hm maybe it would be cool to also be able to force it with a variable, like some of the other pipelines. (master+tags+variable)
I'll see what I can do.

**Comment by patrickvacek** [comment]
> Hm maybe it would be cool to also be able to force it with a variable, like some of the other pipelines. (master+tags+variable)

Could be cool but don't sweat that. This is pretty cool all is.

> Before I've limited it to master and tags: https://main.gitlab.in.here.com/olp/edge/ota/connect/client/aktualizr/pipelines/49676

Thanks! I see this bit:
```
+ TEST_AKTUALIZR_BRANCH=ci/OTA-2465/aktualizr-oe
+ TEST_AKTUALIZR_REV=12e26566874682ecb677b597e440f5d99f6b69ef
```
But is there a way to be sure that that's really what ptest ran?

**Comment by lbonn** [comment]
Good point. The way I've tested it is to log in the docker image while it's running and cat-ing `site.conf`. Maybe we should just cat it in the configure script in any case.

**Comment by lbonn** [comment]
https://main.gitlab.in.here.com/olp/edge/ota/connect/client/aktualizr/pipelines/50185

**Comment by lbonn** [comment]
Needs https://github.com/advancedtelematic/meta-updater/pull/563 for working with the tag.

**Comment by lbonn** [comment]
Ok, finally shown to work with tags and manual triggers!

**Comment by patrickvacek** [comment]
> I'm assuming whyever Travis failed is bogus.

It worked after a restart!

**Pull request merged**
