### PR TITLE
Add option for implicit-writer to skip writing root certificate

### PR DESCRIPTION
**Pull request by OYTIS**
Extracting root.crt from bootstrap.p12 doesn't work in some cases:
1. openssl (which we use for PKCS#11 case) doesn't work with root.crt stored in bootstrap credentials, it needs the issuer of client certicate there as well.
2. Bootstrap credentials don't contain the certificate for S3 servers and will therefore fail on staging environment (and on production when redirection to AWS is merged into production).

It is therefore convenient to have an option to suppress output of root.crt.

### CODE REVIEW

**Comment by patrickvacek** [comment]
How do we got about solving those two problems?

**Comment by OYTIS** [comment]
Temporary solution is just to use root.crt provided by cert_provider. Permanent solution would be to pack everything necessary in the root.crt we get as a part of implicit provisioning credentials package.

**Comment by patrickvacek** [comment]
Okay, that sounds like what I was thinking. Kind of a server-side issue in generating the package, right? I suppose we could do some fiddling with the root.crt in implicit_writer, but I'm not too excited about that.

**Comment by OYTIS** [comment]
> I suppose we could do some fiddling with the root.crt in implicit_writer, but I'm not too excited about that.

Not really. The missing data is really missing, it can only be found in the package we receive as a result of device registration.

**Comment by cajun-rat** [comment]
@koshelev Where should we be getting the root CA from?

**Comment by patrickvacek** [comment]
#2 is going to be a bug for the non-implicit case, too, right? How will a device bootstrap itself if it needs the S3 cert and doesn't have it?

**Comment by OYTIS** [comment]
@patrickvacek No, we only need S3 credentials for pulling from treehub. For device registration what we have in bootstrap.p12 is enough.

**Pull request merged**
