### PR TITLE
Feat/pro 5333/jenkins test all

### PR DESCRIPTION
**Pull request by lbonn**

### CODE REVIEW

**Comment by lbonn** [comment]
After a lot of trials and error, it should be ready.

Two issues (valgrind related) I couldn't fix:

- PRO-5338: leak with P11 tests => suppressed in valgrind for now
- leaks in `test_uptane`, only on debian testing, I'll open an issue for them => test result ignored on jenkins for now

**Comment by cajun-rat** [comment]
Can we disable these on Travis somehow?

**Comment by lbonn** [comment]
`test_uptane leaks` tracked in PRO-5358

**Comment by lbonn** [comment]
Passing both CIs now, waiting for your reviews :)

**Comment by cajun-rat** [comment]
Nice.  Good to see that some of those were real leaks too :)

**Pull request merged**
