### PR TITLE
Docs/minor updates

### PR DESCRIPTION
**Pull request by patrickvacek**

### CODE REVIEW

**Comment by lbonn** [comment]
I think the tests did not run on gitlab because the branch name starts with `docs/`

**Comment by patrickvacek** [comment]
> I think the tests did not run on gitlab because the branch name starts with `docs/`

Correct. No need to run them here, right?

**Comment by lbonn** [comment]
@patrickvacek no it's fine, but I was not sure it was intended?

**Comment by patrickvacek** [comment]
> @patrickvacek no it's fine, but I was not sure it was intended?

In this case, yes.

**Pull request merged**
