### PR TITLE
Refact/packman/cleanup interface

### PR DESCRIPTION
**Pull request by mike-sul**

### CODE REVIEW

**Comment by mike-sul** [comment]
depends on https://github.com/advancedtelematic/aktualizr/pull/1548

**Comment by lbonn** [comment]
Looks good!

**Comment by mike-sul** [comment]
@eu-smirnov I think, this change is in line with the discussion we had during reviewing of the ostree update on Secondary PR, I mean getting rid of dependency on bootloader in sotauptaneclient and cleaning the package manager interface from the related methods.

**Comment by eu-smirnov** [comment]
@mike-sul Sorry, I'm a little bit late, but yes, that looks good to me!

**Comment by lbonn** [comment]
Ah sorry, maybe it was me being too fast.

**Pull request merged**
