### PR TITLE
Multi install fix

### PR DESCRIPTION
**Pull request by patriotyk**

### CODE REVIEW

**Comment by cajun-rat** [comment]
This has a workaround for a potentially broken test in the uptane-test-vectors.  Need to investigate that first

**Comment by cajun-rat** [comment]
This is blocked by https://advancedtelematic.atlassian.net/browse/PRO-3591

**Comment by OYTIS** [comment]
@patriotyk This approach doesn't work as expected. I'll rebase my solution on your new commit and re-commit it, please don't overwrite it.

**Comment by patriotyk** [comment]
Sorry, I missed Your commits, I just figured out it from the email

**Comment by OYTIS** [comment]
@patriotyk Oh, sorry, you've already implemented half of it (and in a better organized way). I'll push the other half and test.

**Comment by OYTIS** [comment]
@patriotyk @cajun-rat I also see some strange error in RunForeverNoUpdates test. Looks like it expects some different sequence of events than what we provide.

**Pull request closed without merging**
