### PR TITLE
Set an `ecu_serial` in example virtualsec.json

### PR DESCRIPTION
**Pull request by lbonn**
It is actually needed.

Thanks @EpicNuts!

### CODE REVIEW

**Comment by lbonn** [comment]
Yes but that's probably a bug. I have seen error messages that ends with `error ... with Ecu: `.

If you look in the code, it reads it from the Json and just picks an empty serial if it's not there.

**Comment by patrickvacek** [comment]
> it reads it from the Json and just picks an empty serial if it's not there.

I see, that's probably not ideal. We should complain if someone tries to do that. I was hoping that one was generated for virtual secondaries, but if we don't do that, we shouldn't allow empty serials at all.

**Comment by lbonn** [comment]
Hmm ok I overlooked some stuff...
https://github.com/advancedtelematic/aktualizr/blob/348822d914f422a8d7b34a1e98cfdd1fa3cf816c/src/libaktualizr/config/config_test.cc#L127

https://github.com/advancedtelematic/aktualizr/blob/348822d914f422a8d7b34a1e98cfdd1fa3cf816c/src/libaktualizr/uptane/managedsecondary.h#L29

The message I saw was probably an early error during initialization, maybe we should just fix that.

**Comment by patrickvacek** [comment]
> maybe we should just fix that

Sure. I was pretty sure there were hacks to make it fairly "user-friendly". I think I recall specifically trying to allow not specifying the serial (for virtual secondaries only!) so that we could make testing easier. Otherwise you run into problems with reusing the serial with the same account. Maybe that is less of a problem now, but it used to be worse.

**Comment by lbonn** [comment]
Closing it for now

**Pull request closed without merging**
