### PR TITLE
Trigger poll event in poll event processor to avoid accumulation of events

### PR DESCRIPTION
**Pull request by OYTIS**
Accumulation gets especially annoying when debugging aktualizr, but can also slow everything down if network connection is slow/unstable.

### CODE REVIEW

**Comment by cajun-rat** [comment]
I think the CI error with this is real--I get the following from test_uptane:


    terminate called after throwing an instance of 'std::logic_error' 
    what():  Attempt to write to closed channel.

**Comment by OYTIS** [comment]
@cajun-rat 
It is. Looks like nobody is really closing it, it just gets out of scope with unpredictable result. I made it a shared pointer everywhere, hope that helps. Also I removed this exception, because if somebody desides to use close() it will be subject to run condition (or we'll need an atomic operation 'check if not closed and write' on a Channel).

**Comment by OYTIS** [comment]
Maybe it's also worth making events_channel a shared pointer just for symmetry (and to avoid future problems of course).

**Comment by cajun-rat** [comment]
(Rebased)

**Comment by cajun-rat** [comment]
Approved, subject to CI passing.

**Pull request merged**
