### PR TITLE
 Add flag to create directories for writeFile

### PR DESCRIPTION
**Pull request by patriotyk**

### CODE REVIEW

**Comment by patrickvacek** [comment]
Looks good, but the next step is to actually make use of the option throughout the code base! I know there are many places where we check if a directory exists and make it if it doesn't already, and that can now be simplified with this option.

**Comment by patriotyk** [comment]
Do You suggest me to do that in this PR?

**Comment by patrickvacek** [comment]
@patriotyk Yeah, that was my intention, although admittedly I didn't make that clear when I wrote the ticket. Just do a quick search for places that call writeFile and see if they can benefit from the new option.

**Comment by patriotyk** [comment]
Ok

**Comment by patriotyk** [comment]
Done, but there is no so many places. I found only two.

**Pull request merged**
