### PR TITLE
Check that a config dir exists before using it.

### PR DESCRIPTION
**Pull request by patrickvacek**
AktualizrInfoConfig now inherits from BaseConfig just like the other configs.

### CODE REVIEW

**Comment by patrickvacek** [comment]
Crap, do not merge. This fix breaks tests.

**Comment by patrickvacek** [comment]
> assuming the Jenkins box doesn't pass out.

Travis doesn't seem to be doing much better...

**Comment by lbonn** [comment]
There are some clang-tidy warnings, I'll push a fix here

**Comment by lbonn** [comment]
Ooops, I merged before pushing here, sorry... I've added directly the fix to master afterwards

**Pull request merged**
