### PR TITLE
Fix 'make qa'

### PR DESCRIPTION
**Pull request by cajun-rat**
Change-Id: I2043ebaca9aa442e59cf86e2d3df07c369f5581f

### CODE REVIEW

**Comment by lbonn** [comment]
Also stumbled on that yesterday and included the fix into https://github.com/advancedtelematic/aktualizr/pull/617. Maybe I should do smaller PRs...

**Comment by lbonn** [comment]
Also: this passed on Travis because tests are run as root inside the docker container.

To catch these kinds of test bugs, we might want to run as an unprivileged user inside the container.

**Comment by cajun-rat** [comment]
Yes, we should fix that run as root thing.  I'm going to close this PR in preference to #617.  But yes, smaller PRs are bettr :)

**Comment by patrickvacek** [comment]
+1 to not running tests as root.

**Pull request closed without merging**
