### PR TITLE
Real fix for CI creds

### LINKED ISSUE #959: aktualizr release tarballs do not include sub modules
The sub modules are missing in the release tarball. This does not allow to build from release tarballs...

### PR DESCRIPTION
**Pull request by lbonn**
Also build a full source archive! (Fixes #959)

Example here: https://github.com/advancedtelematic/aktualizr/releases/tag/2019.3-test (will remove when we'll have the proper 2019.3)

Sorry for all the noisy test releases...

### CODE REVIEW

**Comment by lbonn** [comment]
I don't know if there is a simple setting but it should be possible through that https://developer.github.com/v3/repos/releases/#delete-a-release-asset. Though, it could also be tedious to do set it up, so we might as well do it manually as it is quite manageable given the frequency of our releases.

**Comment by lbonn** [comment]
That's quite annoying that our coverage keeps timing out at 50 min on Travis... :/

**Comment by patrickvacek** [comment]
> That's quite annoying that our coverage keeps timing out at 50 min on Travis... :/

Yeah I'll say. Did something suddenly change to cause that? Travis seems to be particularly slow lately.

**Comment by lbonn** [comment]
> I'd say it's fine for now, but we want to get the release process tidied up sooner or later, so I'd like to see this automated as well, but not necessarily in this PR!

I see your point but having these extraneous files shouldn't be too much of a problem if documented correctly.
Also, I took another look and they are not removeable from the gui and don't appear in the list of assets in the api either:

```
$ curl https://api.github.com/repos/advancedtelematic/aktualizr/releases | jq '.[0].assets[].name'
"aktualizr-ubuntu_16.04.deb"
"aktualizr-ubuntu_18.04.deb"
"aktualizr_src-2019.3-test.tar.gz"
"garage_deploy-ubuntu_16.04.deb"
"garage_deploy-ubuntu_18.04.deb"
```

So, probably a lost cause...

> Yeah I'll say. Did something suddenly change to cause that? Travis seems to be particularly slow lately.

It's maybe just the steady growth in our number of expensive tests, combined with the variability in Travis run times.

```
...
107/111 Test  #18: test_uptane .........................................   Passed  651.97 sec
109/111 Test #107: memory_test .........................................   Passed  113.03 sec
110/111 Test #103: test_uptane_vectors .................................   Passed  144.68 sec
111/111 Test  #12: test_aktualizr ......................................   Passed  849.37 sec
```

**Comment by patrickvacek** [comment]
> 111/111 Test  #12: test_aktualizr ......................................   Passed  849.37 sec

It's really time to split this into smaller tests... 14 minutes is way too much for one test set.

**Comment by lbonn** [comment]
@patrickvacek oddly, in the last run it stalled during the codecov step https://travis-ci.org/advancedtelematic/aktualizr/jobs/526486686. It didn't print any output for at least 1 minute, so there could be some other problem involved...

**Pull request merged**
