### PR TITLE
Support extracting client certificate from PKCS#11 device

### PR DESCRIPTION
**Pull request by OYTIS**
device_id file is used in end-to-end tests.

### CODE REVIEW

**Comment by patrickvacek** [comment]
This compiles and passes all tests, but should we have a specific test case for testing this functionality? And is there a convenient way to test this end-to-end, or is that still underway as part of the rest of the p11 work? Generally I think this looks fine, though.

**Comment by OYTIS** [comment]
@patrickvacek 
Yes, testing can be a bit tricky, I suspect that when we import a certificate into SoftHSM only first one really gets imported, so we can't just compare the textual versions. Extracting a device ID can be a good test, I'll write that one.

**Comment by OYTIS** [comment]
@patrickvacek 
Oh, yes how you can see it's using pkcs11. The only thing that is currently in the log is the listing of a token's properties, it can be found in the beginning of the log. Other than that you can just distingush two working modes by looking into sota.toml. Do you need any additional information in the logs?

**Comment by patrickvacek** [comment]
I have aktualizr sort of working and I see the log message now. That should be fine. However, now I'm seeing errors like this:
```
* <url> malformed
* Closing connection -1
[2017-10-16 09:53:18.294106]: curl error 3: URL using bad/illegal format or missing URL
```
...and `The director repo is missing.`

**Pull request merged**
