### PR TITLE
Revert source code to 2019.5 state

### PR DESCRIPTION
**Pull request by tkfu**
The 2019.5-docs branch was an attempt to clean up the branch so that it only had the docs-relevant commits in it. This involved a pretty massive cherry-pick, and many of the cherry-picked commits included changes to both code and docs. (I also may have gotten a bit sloppy in resolving merge conflicts outside of the docs directory.)

This PR just takes out a shotgun and reverts everything except for the docs directory to the way it was when 2019.5 was released. That's the "correct" state for this branch to be in according to our new versioning policy; the only differences between this branch and tag 2019.5 are in the docs directory. (You can also verify that the docs changes are correct by diffing the docs directory on this branch against the docs directory in 2019.05; they're identical.)

### CODE REVIEW

**Comment by OYTIS** [comment]
This pull request **fixes 1 alert** when merging c9111943c73848a08d8ba38fd89d32bb9cb81bc9 into 676ef9b777a04db7f5abd686aeac5fca1d3affd8 - [view on LGTM.com](https://lgtm.com/projects/g/advancedtelematic/aktualizr/rev/pr-8ca41c8dcbc6ffc62a641aa744f229702e8a9d4f)

**fixed alerts:**

* 1 for Syntax error

---

**Warning** - Automated code review for advancedtelematic/aktualizr will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by patrickvacek** [comment]
I still don't think this is right. CI is still quite unhappy, and I see commits already in the 2019.5-docs that shouldn't be there, like renaming aktualizr-repo to uptane-generator. I think I can rebase the branch and remove the bits that shouldn't be there in the first place if you'll allow it, but this will require a force-push. Perhaps I can maybe a candidate branch first to show you what I mean if you'd like.

**Comment by lbonn** [comment]
I would also prefer a rebase + force push. This is too confusing.

**Comment by tkfu** [comment]
I agree that it's confusing, and a rebase and force-push is probably the right thing to do. But I don't think there's a very easy fix that gets the docs for this branch right according to our [new versioning policy](https://github.com/advancedtelematic/adr/blob/master/0007-aktualizr-docs-release-process.md]--which is understandable, because it predates that policy. It's also the first docs branch with the Antora stuff, so it's got a big and messy commit history; there are definitely docs changes mixed into that messy history that don't actually apply to 2019.5.

> I see commits already in the 2019.5-docs that shouldn't be there, like renaming aktualizr-repo to uptane-generator. I think I can rebase the branch and remove the bits that shouldn't be there in the first place

If you feel like it's worth the time to do that, I'd be grateful. My personal evaluation was that it would take an amount of time, close reading, and git fuckery that just wouldn't be worth it for a bit of extra correctness in the docs for an old version. That's why I was willing to just settle for getting this branch to render the current status quo on the docsite, while getting at least the branch name correct and having the code on the branch be the aktualizr-2019.5 code. If we find mistakes that people complain about, or that we think are worth correcting, we can always fix them later.

**Comment by patrickvacek** [comment]
> If you feel like it's worth the time to do that, I'd be grateful.

Challenge accepted. Doesn't seem too hard to me.

**Comment by patrickvacek** [comment]
Closing in favor of https://github.com/advancedtelematic/aktualizr/pull/1363.

**Pull request closed without merging**
