### PR TITLE
OTA-2851: Support ostree refs posting by the test treehub server

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mike Sul <ext-mykhaylo.sul@here.com>

### CODE REVIEW

**Comment by mike-sul** [comment]
> Looks fine, but would you mind writing a test that uses this feature? Or is there more code to come that will make use of this?

Do we have tests that test treehub_server.py explicitly ?

**Comment by patrickvacek** [comment]
> Do we have tests that test treehub_server.py explicitly ?

Not exactly, but several tests use it, so I was just wondering if it made sense to write a test that used this functionality. If it's just exploratory, that's okay too.

**Comment by mike-sul** [comment]
> > Do we have tests that test treehub_server.py explicitly ?
> 
> Not exactly, but several tests use it, so I was just wondering if it made sense to write a test that used this functionality. If it's just exploratory, that's okay too.

OK, I got it, I'll check out if I can extend one of the existing tests or a new one based on the existing one in such way that the functionality I added is used and implicitly tested.

**Comment by patrickvacek** [comment]
Sounds fine. It's not a big deal, I just wanted some proof that the code works as expected. Since this is just test code, a quick example/demo/whatever is also fine.

**Comment by mike-sul** [comment]
Extended `deploy_test` with functionality that pushes a ref from a source repo to a destination one and implicitly tests the functionality I added to the test treehub server.

**Pull request merged**
