### PR TITLE
test-aktualizr-reject-updates-different-sizes

### PR DESCRIPTION
**Pull request by Zee314159**
Removed redundant `OversizedTarget` error.

### CODE REVIEW

**Comment by patrickvacek** [comment]
Now that https://github.com/advancedtelematic/tuf-test-vectors/pull/59, the tuf-test-vectors version should get changed to the final version and then we can merge this!

**Comment by Zee314159** [comment]
> Now that advancedtelematic/tuf-test-vectors#59, the tuf-test-vectors version should get changed to the final version and then we can merge this!

The tuf-test-vectors is updated to the final version in this repository.

**Comment by patrickvacek** [comment]
> The tuf-test-vectors is updated to the final version in this repository.

It looks like it is still pointing at [ca89999a287594695798cf2bca0e40ae31aba25d](https://github.com/advancedtelematic/tuf-test-vectors/commit/ca89999a287594695798cf2bca0e40ae31aba25d), but it should be pointing at the merge commit ([70c7b23369b4164912d2672574355598a3e4ebdf](https://github.com/advancedtelematic/tuf-test-vectors/commit/70c7b23369b4164912d2672574355598a3e4ebdf)).

**Comment by Zee314159** [comment]
> The tuf-test-vectors is updated to the final version in this repository.
> 
> It looks like it is still pointing at ca89999a287594695798cf2bca0e40ae31aba25d, but it should be pointing at the merge commit (70c7b23369b4164912d2672574355598a3e4ebdf).

Fixed.

**Pull request merged**
