### PR TITLE
2019.5 docs fixed

### PR DESCRIPTION
**Pull request by patrickvacek**
This is a fake PR just to show exactly what I think is worth keeping from what's currently in 2019.5-docs starting from where the 2019.5-docs branch should have been created (i.e. the 2019.5 tag).

### CODE REVIEW

**Comment by patrickvacek** [comment]
Oops, I screwed something up...

**Comment by patrickvacek** [comment]
Still have some more things that need to be removed. I'll sort it out after lunch.

**Comment by patrickvacek** [comment]
Ready for review now, I think.

`git diff fix/2019.05-docs/secondary-config` indicates that this branch (correctly) leaves out a bunch of stuff that should be in that branch. The only thing I left out that might be desirable is the meta-updater doc migration.

**Comment by tkfu** [comment]
> The only thing I left out that might be desirable is the meta-updater doc migration.

Unfortunately, we're gonna need that--in the branch as it currently stands, `build-configuration.adoc` and `supported-boards.adoc` have includes from meta-updater, which will no longer work.

**Comment by tkfu** [comment]
In general this LGTM. If you add in the stuff to fix the broken includes and merge my syntax fixes from #1367 in, I'm happy for you to force-push this to 2019.5-docs.

**Comment by patrickvacek** [comment]
> If you add in the stuff to fix the broken includes and merge my syntax fixes from #1367 in, I'm happy for you to force-push this to 2019.5-docs.

Done!

**Pull request closed without merging**
