### PR TITLE
Use boost::process consistently across all tests

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mike Sul <ext-mykhaylo.sul@here.com>

### CODE REVIEW

**Comment by lbonn** [comment]
Do you intend to push more commits on top, with changes in the other tests to remove `TestHelperProcess`? The title of the PR seems to imply more work.

**Comment by mike-sul** [comment]
> Do you intend to push more commits on top, with changes in the other tests to remove `TestHelperProcess`? The title of the PR seems to imply more work.

Not sure yet, if it worth doing, let me check it out once more.
@lbonn What's you opinion on it ?

**Comment by lbonn** [comment]
From a quick glance, it doesn't look too hard. Most of our other uses are trivial.
It that's indeed easy, I think that's a good idea to replace them.

**Comment by mike-sul** [comment]
> From a quick glance, it doesn't look too hard. Most of our other uses are trivial.
> It that's indeed easy, I think that's a good idea to replace them.

Yes, I am gonna to do it.

**Comment by lbonn** [comment]
Found some remaining uses with grep: https://github.com/advancedtelematic/aktualizr/blob/94970eb2ef2ad51a3aa86953f74ecbb6237199cd/src/libaktualizr/opcuabridge/opcuabridge_messaging_test.cc#L159

Dormant code, but I think we still build it on CI

**Comment by mike-sul** [comment]
> Found some remaining uses with grep:
> 
> [aktualizr/src/libaktualizr/opcuabridge/opcuabridge_messaging_test.cc](https://github.com/advancedtelematic/aktualizr/blob/94970eb2ef2ad51a3aa86953f74ecbb6237199cd/src/libaktualizr/opcuabridge/opcuabridge_messaging_test.cc#L159)
> 
> Line 159 in [94970eb](/advancedtelematic/aktualizr/commit/94970eb2ef2ad51a3aa86953f74ecbb6237199cd)
> 
>  TestHelperProcess server("./opcuabridge-server", opc_port); 
> Dormant code, but I think we still build it on CI

Yeah, for some reason qtcreator didn't index that file as well as opcuabridge_secondary_update_test.cc.

**Comment by lbonn** [comment]
> Yeah, for some reason qtcreator didn't index that file as well as opcuabridge_secondary_update_test.cc.
If it relies on CMake, that's probably because it used a build directory in which BUILD_OPCUA was not set to `on`.

**Pull request merged**
