### PR TITLE
OLPSUP-8795: Import the initial hash from file for IP Secondary

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mykhaylo Sul <myk.sul@gmail.com>

### CODE REVIEW

**Comment by lbonn** [comment]
Nice. Do you think adding a non-regression test would be possible here?

**Comment by mike-sul** [comment]
> Nice. Do you think adding a non-regression test would be possible here?

Everything is possible :). The question is if it is reasonable. I am just not sure if the current approach to setting of the initial version is the right one. If not, then we have to rework it, so adding test to something that we are going to throw away does not make sense, otherwise I can add some test. Let's discuss it tomorrow during the meeting.

**Comment by patrickvacek** [comment]
To summarize discussion: testing is of course a great idea, but since we think we want to redo this logic really soon anyway, perhaps a test for this quick-fix logic is not such a great use of our time.

**Comment by mike-sul** [comment]
@lbonn @patrickvacek  please, check out if I updated the changelog correctly.

**Pull request merged**
