### PR TITLE
Add A3 overview diagram

### PR DESCRIPTION
**Pull request by cajun-rat**

### CODE REVIEW

**Comment by patriotyk** [comment]
This svg file displays incorrectly on my laptop and on github preview page
screenshot 2017-05-22 at 16 19 03

**Comment by cajun-rat** [comment]
Yeah, it needs inkscape to view it. Checking in the PDF might help?

**Comment by patriotyk** [comment]
SVG is good to, but You just need to convert all text to curves and save it as plain svg(not inkscape)

**Comment by cajun-rat** [comment]
Updated, I now build the PDF automatically, if inkscape is detected.

I'd rather not convert all the text to curves, because that will make it hard to edit

**Comment by cajun-rat** [comment]
Nudge :)

**Pull request merged**
