### PR TITLE
OTA-2487: OTA-2544: Remove the secondary discovery mechanism

### PR DESCRIPTION
**Pull request by mike-sul**
As it was decided to preconfigure Primary with Secondary IPs the current discovery mechanism becomes irrelevant.

### CODE REVIEW

**Comment by patrickvacek** [comment]
When I run `grep discovery -rIin * --exclude-dir=build/ --exclude-dir=partial/ --exclude=tags --exclude=cscope.*` I still see some things. Some may still be relevant, but the actions, config, and docs can almost certainly get cleansed of these references.

**Comment by mike-sul** [comment]
> When I run `grep discovery -rIin * --exclude-dir=build/ --exclude-dir=partial/ --exclude=tags --exclude=cscope.*` I still see some things. Some may still be relevant, but the actions, config, and docs can almost certainly get cleansed of these references.

Yeah, your're right, i just removed the check-discovery and the Secondary's part of discovery, while the Primary's part and corresponding tests still there. Will update this PR.

**Comment by OYTIS** [comment]
This pull request **fixes 1 alert** when merging 544a07f9b711568cbfcfba38d05f67c79446252f into 2a32803a6f8e6a6dd0e6323697b7941dd8bd417e - [view on LGTM.com](https://lgtm.com/projects/g/advancedtelematic/aktualizr/rev/pr-d7a263d80cd2d3b3e0cdd0de785df662761e7e5f)

**fixed alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by patrickvacek** [comment]
Also looks like there is a really pedantic clang-format complaint.

**Comment by mike-sul** [comment]
> Looks about right, but I still see a couple discovery references in `src/libaktualizr-posix/asn1/messages/ipuptane_message.asn1` that I think can be removed.
> Also looks like there is a really pedantic clang-format complaint.

Should be fine now.

**Comment by OYTIS** [comment]
This pull request **fixes 1 alert** when merging fa5c80aac0ebcb96daa83bb1c64fdf43582797d9 into de05467c1f7b4098e0972154e3d8e7bf3b5bc6f8 - [view on LGTM.com](https://lgtm.com/projects/g/advancedtelematic/aktualizr/rev/pr-d2d3530a7fd0da63f7b8271373814dc8d15887d6)

**fixed alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by mike-sul** [comment]
> Also looks like there is a really pedantic clang-format complaint.

maybe, it's too pedantic :)

**Comment by OYTIS** [comment]
This pull request **fixes 1 alert** when merging 3f3d442ac445fad9c9584e156d94bde3633a4fed into de05467c1f7b4098e0972154e3d8e7bf3b5bc6f8 - [view on LGTM.com](https://lgtm.com/projects/g/advancedtelematic/aktualizr/rev/pr-6efbccd463d1e6abce5329f96faa0f2a068ba0e6)

**fixed alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
