### PR TITLE
Add a targets iterator

### PR DESCRIPTION
**Pull request by doanac**
This is related to issue:
  https://github.com/advancedtelematic/aktualizr/issues/1056
    
In order for an application to find the latest target, it will need
access to the list of targets found in the image repository.

I considered using a C++ iterator for this and before the delegation
merge it wasn't too bad. However, doing this as an iterator was
requiring keeping state of 3 iterators (the toplevel, the delegated roles,
and targets for a delegated role) and the resulting code seemed a
bit awkward compared to this.

I'm totally open to alternatives from you guys, but I thought I'd try 
and see if this might be okay. Feel free to just cherry-pick the
unit-test if you want that and nothing else :)

### CODE REVIEW

**Comment by OYTIS** [comment]
This pull request **introduces 1 alert** when merging e1a210c56d1890f6eb2165030bf5745c915ff46b into 49bc10b601c5a67719b8caa08c3ccebd4d5a454f - [view on LGTM.com](https://lgtm.com/projects/g/advancedtelematic/aktualizr/rev/pr-dbe407ea07609ee7499f8b52c5cdf9aecea132d0)

**new alerts:**

* 1 for Resource not released in destructor

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by OYTIS** [comment]
@doanac Thanks a lot, I'll look into that. One partially relevant question regarding tuf-tree: I was trying to play around with tuftree example backend to have something to test anonymous mode against. And apparently 'notary' is not public in 'foundriesio' dockerhub repo, and I get 'pull access denied' error. Could you open it or is it not intended to be public?

**Comment by doanac** [comment]
@OYTIS - You have a typo for the notary containers. Our dockerhub is just "foundries" not foundriesio: https://hub.docker.com/r/foundries/notary/

**Comment by lbonn** [comment]
@doanac I think this should work and make LGTM happy:

```
std::unique_ptr<Uptane::Target> ImagesRepository::getTarget(const Uptane::Target& director_target) {
  std::unique_ptr<Uptane::Target> rv;
  auto cb = [director_target, &rv](const Uptane::Target& t) {
    if (director_target == t){
      rv = std_::make_unique<Target>(t);
      return false;
    }
    return true;
  };
  iterateTargets(cb);
  return rv;
}
```

**Comment by OYTIS** [comment]
@doanac Sorry for the delay, we've found some problems with delegations and will spend some days rewriting. After that we'll make a new PR based on your contribution. Thanks a lot!

**Comment by OYTIS** [comment]
Alternative implementation (https://github.com/advancedtelematic/aktualizr/pull/1104) has been merged, closing.

**Pull request closed without merging**
