### PR TITLE
Update changelog for a new release.

### PR DESCRIPTION
**Pull request by patrickvacek**
I'd like to make a new release for @stevana. Any objections?

### CODE REVIEW

**Comment by lbonn** [comment]
Should we wait for the auto-reboot to land, or does it answer an urgent concern?

**Comment by patrickvacek** [comment]
> Should we wait for the auto-reboot to land, or does it answer an urgent concern?

Sure, I think we can wait for that. Shouldn't be too long now, anyway!

**Comment by patrickvacek** [comment]
Rebased.

**Comment by patrickvacek** [comment]
Jenkins is finally happy. The Travis error is bogus. Anyone want to take a look while the date in the text is still accurate?

**Comment by patrickvacek** [comment]
Merging since this is docs-only, small, presumably uncontroversial, and the date is embedded in the commit.

**Pull request merged**
