### PR TITLE
Tests/ota 1353/actions update

### PR DESCRIPTION
**Pull request by patrickvacek**
Mostly documentation and comments, but a few minor fixes to various tests.

### CODE REVIEW

**Comment by lbonn** [comment]
Great work! We still have some of these unstable tests causing trouble unfortunately.

**Comment by patrickvacek** [comment]
Rebased and removed my failed attempt to fix `authenticate_test`'s `good_cert_zip` test case. We'll have to come back to that another time.

**Comment by patrickvacek** [comment]
I think I've finally fixed one of the broken tests (`test-missing-commit`). I broke it further in this PR and fixed both problems with it. I have no idea how this worked before. `set -e` and `set -o pipefail` were both disastrous for that test.

**Comment by patrickvacek** [comment]
@lbonn No, those are valid points. It took seconds to fix them, so I did. I left `exit $?` for now just to be explicit.

**Pull request merged**
