### PR TITLE
wait more time for server start

### PR DESCRIPTION
**Pull request by patriotyk**

### CODE REVIEW

**Comment by cajun-rat** [comment]
Is there any way we can wait until it has actually started, rather than adding more sleep()?

**Comment by patriotyk** [comment]
We could try to connect to 80 port in loop

**Comment by cajun-rat** [comment]
What about making the script pick a random port number, and write it to a temporary named pipe that is  passed in on the command line?

That would also let the tests run in parallel, which would save a huge amount of time?

**Comment by cajun-rat** [comment]
I'll merge this as a temporary fix.  A proper solution (that doesn't require sleep() calls) can come as part of the work to be able to run the tests in parallel (i.e. removing CTEST_PARALLEL_LEVEL=1)

**Pull request merged**
