### PR TITLE
Implemented uptane verification and covered with tests

### PR DESCRIPTION
**Pull request by patriotyk**

### CODE REVIEW

**Comment by cajun-rat** [comment]
@patriotyk I'm seeing a couple of errors on my local build that don't appear to be happening on the CI system.  Any idea what might be causing them?

```
ninja qa -j1
[1/4] cd /home/phil/work/aktualizr/build && CTEST_OUTPUT_ON_FAILURE=1 CTEST_PARALLEL_LEVEL=1 /usr/bin/ctest
FAILED: cd /home/phil/work/aktualizr/build && CTEST_OUTPUT_ON_FAILURE=1 CTEST_PARALLEL_LEVEL=1 /usr/bin/ctest
Test project /home/phil/work/aktualizr/build
      Start  1: test_config
 1/17 Test  #1: test_config ......................   Passed    0.01 sec
      Start  2: test_events
 2/17 Test  #2: test_events ......................   Passed    0.00 sec
      Start  3: test_commands
 3/17 Test  #3: test_commands ....................   Passed    0.00 sec
      Start  4: test_http_aktualizr
 4/17 Test  #4: test_http_aktualizr ..............***Failed    0.01 sec
[==========] Running 6 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 1 test from AuthenticateTest
[ RUN      ] AuthenticateTest.authenticate_called
[       OK ] AuthenticateTest.authenticate_called (0 ms)
[----------] 1 test from AuthenticateTest (0 ms total)

[----------] 2 tests from DownloadTest
[ RUN      ] DownloadTest.download_called
[       OK ] DownloadTest.download_called (1 ms)
[ RUN      ] DownloadTest.download_error
[       OK ] DownloadTest.download_error (0 ms)
[----------] 2 tests from DownloadTest (1 ms total)

[----------] 1 test from GetAvailableUpdatesTest
[ RUN      ] GetAvailableUpdatesTest.get_performed
[       OK ] GetAvailableUpdatesTest.get_performed (0 ms)
[----------] 1 test from GetAvailableUpdatesTest (0 ms total)

[----------] 1 test from ReportTest
[ RUN      ] ReportTest.post_called
[       OK ] ReportTest.post_called (0 ms)
[----------] 1 test from ReportTest (0 ms total)

[----------] 1 test from SotaHttpClientTest
[ RUN      ] SotaHttpClientTest.device_registered
[2017-03-21 11:38:27.478934] [0x00007face60ab740] [info]    auth.client_id not in config file. Using default:client-id
[2017-03-21 11:38:27.478952] [0x00007face60ab740] [info]    auth.client_secret not in config file. Using default:client-secret
[2017-03-21 11:38:27.478954] [0x00007face60ab740] [trace]   dbus.software_manager not in config file. Using default:org.genivi.SoftwareLoadingManager
[2017-03-21 11:38:27.478957] [0x00007face60ab740] [trace]   dbus.software_manager_path not in config file. Using default:/org/genivi/SoftwareLoadingManager
[2017-03-21 11:38:27.478959] [0x00007face60ab740] [trace]   dbus.path not in config file. Using default:/org/genivi/SotaClient
[2017-03-21 11:38:27.478961] [0x00007face60ab740] [trace]   dbus.interface not in config file. Using default:org.genivi.SotaClient
[2017-03-21 11:38:27.478963] [0x00007face60ab740] [trace]   dbus.timeout not in config file. Using default:0
[2017-03-21 11:38:27.478984] [0x00007face60ab740] [info]    uptane.director_server not in config file. Using default:
[2017-03-21 11:38:27.478987] [0x00007face60ab740] [info]    uptane.repo_server not in config file. Using default:
[2017-03-21 11:38:27.478996] [0x00007face60ab740] [trace]   config read from tests/config_tests_prov.toml :
	Authentication Server: https://example.com/auth
	Sota Server: https://example.com/core
	Pooling enabled : 0
	Pooling interval : 91
	Client: client-id
	Device UUID: bc50fa11-eb93-41c0-b0fa-5ce56affa63e
[2017-03-21 11:38:27.479071] [0x00007face60ab740] [error]   Could not parse file from 0x25251b0 file pointer
[2017-03-21 11:38:27.479099] [0x00007face60ab740] [error]   Could not parse file from 0x25251b0 file pointer
../tests/httpsotaclient_test.cc:170: Failure
Value of: true
Expected: aktualizr.deviceRegister()
Which is: false
../tests/httpsotaclient_test.cc:171: Failure
Value of: true
Expected: boost::filesystem::exists(conf.device.certificates_path + conf.tls.client_certificate)
Which is: false
../tests/httpsotaclient_test.cc:172: Failure
Value of: true
Expected: boost::filesystem::exists(conf.device.certificates_path + conf.tls.ca_file)
Which is: false
[  FAILED  ] SotaHttpClientTest.device_registered (1 ms)
[----------] 1 test from SotaHttpClientTest (1 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 5 test cases ran. (3 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SotaHttpClientTest.device_registered

 1 FAILED TEST

      Start  5: test_http_client
 5/17 Test  #5: test_http_client .................   Passed    1.01 sec
      Start  6: test_socket_gateway
 6/17 Test  #6: test_socket_gateway ..............   Passed    5.01 sec
      Start  7: test_crypto
 7/17 Test  #7: test_crypto ......................***Failed    0.00 sec
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from crypto
[ RUN      ] crypto.sha256_is_correct
[       OK ] crypto.sha256_is_correct (0 ms)
[ RUN      ] crypto.sign_verify
../tests/crypto_test.cc:25: Failure
Value of: signe_is_ok
  Actual: false
Expected: true
[  FAILED  ] crypto.sign_verify (1 ms)
[----------] 2 tests from crypto (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] crypto.sign_verify

 1 FAILED TEST

      Start  8: test_uptane
 8/17 Test  #8: test_uptane ......................   Passed    0.01 sec
      Start  9: test_dbusgateway
 9/17 Test  #9: test_dbusgateway .................   Passed   18.02 sec
      Start 10: test_rvi_client
10/17 Test #10: test_rvi_client ..................   Passed    6.01 sec
      Start 11: test_swm
11/17 Test #11: test_swm .........................   Passed    4.01 sec
      Start 12: feat1_test--help
12/17 Test #12: feat1_test--help .................   Passed    0.01 sec
      Start 13: feat1_test-h
13/17 Test #13: feat1_test-h .....................   Passed    0.01 sec
      Start 14: feat1_test--something
14/17 Test #14: feat1_test--something ............   Passed    0.01 sec
      Start 15: feat1_test-sth
15/17 Test #15: feat1_test-sth ...................   Passed    0.01 sec
      Start 16: test_plain
16/17 Test #16: test_plain .......................   Passed    0.01 sec
      Start 17: test_log_invalid
17/17 Test #17: test_log_invalid .................   Passed    0.01 sec

88% tests passed, 2 tests failed out of 17

Total Test time (real) =  34.14 sec

The following tests FAILED:
	  4 - test_http_aktualizr (Failed)
	  7 - test_crypto (Failed)
Errors while running CTest
ninja: build stopped: subcommand failed.
```

**Comment by patriotyk** [comment]
On my local env it is ok. Looks like it fails sometimes because previous commits and pull request passes the tests. I am working on resolve this problem

**Comment by cajun-rat** [comment]
Cool, thank you.  One of the CI builds passes and the other fails, which suggests this might be random behaviour?

**Comment by patriotyk** [comment]
Looks like there is an issue in openssl in RSA_public_decrypt function, calling this function corrupts the stack, but it happens sometimes.

**Comment by patriotyk** [comment]
Now it works, and works always ))

**Comment by cajun-rat** [comment]
Excellent

**Pull request merged**
