### PR TITLE
Test installing updates in separate calls.

### PR DESCRIPTION
**Pull request by patrickvacek**
Note, however, that if you were to check for updates between the two calls, that would most likely confuse the backend.

Note that this is meant to cover the case that was broken when https://github.com/advancedtelematic/aktualizr/blob/test/split-update/src/libaktualizr/primary/sotauptaneclient.cc#L896 was not guarded by the `if` clause. I still don't like dropping Targets metadata, but this proves that we can at least do it fairly  safely only if there are problems.

### CODE REVIEW

**Comment by patrickvacek** [comment]
Travis failure seems irrelevant:
```
Error: SQLite database migration failed
ERROR:test_fixtures:None
ERROR:test_fixtures:Failed to get aktualizr info/status
INFO:/aktualizr/tests/test_backend_failure.py:>>> Failed: test_backend_failure_sanity_director_update_after_metadata_download_failure
```
@mike-sul any hints on that one?

**Comment by mike-sul** [comment]
> Travis failure seems irrelevant:
> 
> ```
> Error: SQLite database migration failed
> ERROR:test_fixtures:None
> ERROR:test_fixtures:Failed to get aktualizr info/status
> INFO:/aktualizr/tests/test_backend_failure.py:>>> Failed: test_backend_failure_sanity_director_update_after_metadata_download_failure
> ```
> 
> @mike-sul any hints on that one?

According to the logs aktualizr-info didn't output the desired/expected message.

**Comment by lbonn** [comment]
> Note that this is meant to cover the case that was broken when [/split-update/src/libaktualizr/primary/sotauptaneclient.cc@`test`#L896](https://github.com/advancedtelematic/aktualizr/blob/test/split-update/src/libaktualizr/primary/sotauptaneclient.cc#L896) [](/advancedtelematic/aktualizr/blob/HEAD@{2019-11-25T16:03:35Z}/split-update/src/libaktualizr/primary/sotauptaneclient.cc#L896) was not guarded by the `if` clause. I still don't like dropping Targets metadata, but this proves that we can at least do it fairly safely only if there are problems.

Should we include some of this info in a comment in the test, for easy reference on why it exists?

**Comment by patrickvacek** [comment]
> Should we include some of this info in a comment in the test, for easy reference on why it exists?

Done.

**Pull request merged**
