### PR TITLE
Feat/pro 3792/legacy init

### PR DESCRIPTION
**Pull request by patrickvacek**
This isn't really fully tested yet, but it does pass all the unit tests!

### CODE REVIEW

**Comment by patrickvacek** [comment]
This doesn't actually work in practice yet. I'm looking into why.

**Comment by patrickvacek** [comment]
Cool, this works now! To test, you'll need to copy the myecuinterface built incidentally by bitbaking aktualizr onto the device. We should think about formalizing that. We also need to think more about unit testing this code.

**Comment by cajun-rat** [comment]
I'm going to do a qemu test run then should be good to go

**Comment by patrickvacek** [comment]
Updated with some fixed/improved tests.

**Comment by patrickvacek** [comment]
@cajun-rat  this is theoretically good to go now... if it still works for you.

**Comment by cajun-rat** [comment]
Works on My Machine™

**Pull request merged**
