### PR TITLE
Make name generator a standalone utility

### PR DESCRIPTION
**Pull request by OYTIS**
Maybe it's not a horrible idea. Would be useful in "mock real implicit provisioning" scenario done with openssl utility.

### CODE REVIEW

**Comment by patrickvacek** [comment]
Who else actually needs to use the name generator? Can't we just use it from inside cert_provider?

**Comment by OYTIS** [comment]
@patrickvacek Put openssl logic into cert_provider is more difficult that get name generation out of it. So my current plan is just use 'openssl' utility and give it a name as a parameter. The same problem can also be solved by adding something like `--name-only`, maybe it's a better way.

**Comment by patrickvacek** [comment]
I think I was thinking you could just call the openssl utility from cert_provider with a system call (...or a series of system calls). A bit awkward, but probably no worse than other options. Up to you.

**Comment by OYTIS** [comment]
@patrickvacek OK, it's not a real CA anyway, so we can probably do something simple in plain C without the utility.

**Pull request closed without merging**
