### PR TITLE
ostree: Log status updates of pull

### PR DESCRIPTION
**Pull request by doanac**
Fixes https://github.com/advancedtelematic/aktualizr/issues/670

The changes produce output at loglevel INFO like:

 ostree-pull: Receiving metadata objects: 3
 ostree-pull: Receiving metadata objects: 4
 ostree-pull: Receiving metadata objects: 6
 ostree-pull: Receiving metadata objects: 9
 ostree-pull: Receiving metadata objects: 11
 ostree-pull: Receiving objects: 44%
 ostree-pull: Receiving objects: 83%
 ostree-pull: Receiving objects: 90%
 ostree-pull: Receiving objects: 93%
 ostree-pull: Receiving objects: 97%
 ostree-pull: Writing objects: 1
 ostree-pull: 13 metadata, 16 content objects fetched; 44683 KiB transferred in 23 seconds

Signed-off-by: Andy Doan <andy@opensourcefoundries.com>

### CODE REVIEW

**Comment by cajun-rat** [comment]
Looks good, but there is something about `g_autofree` that is causing the CI to fail. What about using something like https://github.com/advancedtelematic/aktualizr/blob/master/src/libaktualizr/package_manager/ostreemanager.h#L22 : 

```
struct GCharFinalizer {
  void operator()(char *str) const {
    g_free(str);
  }
};

using GCharPtr = std::unique_ptr<char, GCharFinalizer>;
```

**Comment by doanac** [comment]
Just to clarify. I think the issue is with "g_autoptr(OstreeAsyncProgress) progress = NULL;" and not the  "g_autofree char *status = NULL;" based on this:
 https://travis-ci.org/advancedtelematic/aktualizr/jobs/379041277

correct?

**Comment by patrickvacek** [comment]
@doanac Agreed, that it what it looks like, although `/aktualizr/src/src/libaktualizr/package_manager/ostreemanager.cc:37:34: error: 'ostree_async_progress_get' was not declared in this scope` seems concerning, too.

**Comment by doanac** [comment]
yep - i'm running the Dockerfile.nop11 container and I see it has an older ostree that doesn't have this function. Let me re-group on this and figure out how to make this work on the xenia version of ostree.

**Comment by patrickvacek** [comment]
@doanac Sorry about the tedium with CI -- this time it looks like it's complaining about some basic formatting and clang-tidy business. It should be easy enough to fix, though. Here's what looks like the relevant part:

```
/aktualizr/src/src/libaktualizr/package_manager/ostreemanager.cc:23:3: error: use auto when initializing with a cast to avoid duplicating the type name [modernize-use-auto,-warnings-as-errors]
  guint *percent_complete = (guint*)data;
  ^~~~~
  auto
/aktualizr/src/src/libaktualizr/package_manager/ostreemanager.cc:23:29: error: C-style casts are discouraged; use static_cast [google-readability-casting,-warnings-as-errors]
  guint *percent_complete = (guint*)data;
                            ^~~~~~~~~~~~~
                            static_cast<guint*>()
/aktualizr/src/src/libaktualizr/package_manager/ostreemanager.cc:23:29: error: do not use C-style cast to convert between unrelated types [cppcoreguidelines-pro-type-cstyle-cast,-warnings-as-errors]
/aktualizr/src/src/libaktualizr/package_manager/ostreemanager.cc:32:7: error: implicit conversion 'char *' -> bool [readability-implicit-bool-conversion,-warnings-as-errors]
  if (status && *status != '\0') {
      ^~~~~~
      ( != nullptr)
/aktualizr/src/src/libaktualizr/package_manager/ostreemanager.cc:35:12: error: implicit conversion 'guint' (aka 'unsigned int') -> bool [readability-implicit-bool-conversion,-warnings-as-errors]
  else if (outstanding_fetches) {
           ^                  ~
                               != 0u
/aktualizr/src/src/libaktualizr/package_manager/ostreemanager.cc:39:9: error: implicit conversion 'guint' (aka 'unsigned int') -> bool [readability-implicit-bool-conversion,-warnings-as-errors]
    if (scanning || outstanding_metadata_fetches) {
        ^~~~~~~~
        ( != 0u)
/aktualizr/src/src/libaktualizr/package_manager/ostreemanager.cc:39:21: error: implicit conversion 'guint' (aka 'unsigned int') -> bool [readability-implicit-bool-conversion,-warnings-as-errors]
    if (scanning || outstanding_metadata_fetches) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    ( != 0u)
/aktualizr/src/src/libaktualizr/package_manager/ostreemanager.cc:43:34: error: C-style casts are discouraged; use static_cast [google-readability-casting,-warnings-as-errors]
      guint calculated = round((((float)fetched) / requested) * 100);
                                 ^~~~~~~~~~~~~~~
                                 static_cast<float>()
/aktualizr/src/src/libaktualizr/package_manager/ostreemanager.cc:50:12: error: implicit conversion 'guint' (aka 'unsigned int') -> bool [readability-implicit-bool-conversion,-warnings-as-errors]
  else if (outstanding_writes) {
           ^                 ~
                              != 0u
```

**Comment by doanac** [comment]
Thanks for your patience while I get a feel for the development process. I've got clang-format and clang-tidy tests working in my local container now, so hopefully this will pass Travis. Here's an updated view of what the logging looks like:

ostree-pull: Receiving metadata objects: 7 outstanding: 4
ostree-pull: Receiving metadata objects: 8 outstanding: 4
ostree-pull: Receiving objects: 44% 
ostree-pull: Receiving metadata objects: 12 outstanding: 1
ostree-pull: Receiving objects: 69% 
ostree-pull: Receiving objects: 83% 
ostree-pull: Receiving objects: 90% 
ostree-pull: Receiving objects: 93% 
ostree-pull: Receiving objects: 97% 
ostree-pull: 13 metadata, 16 content objects fetched; 44683 KiB transferred in 21 seconds

**Pull request merged**
