### PR TITLE
Remove trace logging from test_fetcher

### PR DESCRIPTION
**Pull request by lbonn**
Way too verbose (~300kB of text)

### CODE REVIEW

**Comment by patrickvacek** [comment]
What all does it spit out? Is debug level better?

**Comment by lbonn** [comment]
These lines, from curl verbose mode

```
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: SimpleHTTP/0.6 Python/3.7.2
< Date: Fri, 22 Mar 2019 10:44:34 GMT
< Content-Type: application/json
< Content-Length: 104857600
<
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
* Expire in 1000 ms for 7 (transfer 0x770d950)
```

They disappear on anything above "trace"

**Comment by patrickvacek** [comment]
> They disappear on anything above "trace"

Gotcha. Then I do suggest debug level.

**Comment by eu-smirnov** [comment]
Strange, I've never seen these lines. Do you know, what is expiring and what is "7"?

**Comment by lbonn** [comment]
Found the source: https://curl.haxx.se/mail/archive-2019-02/0013.html

**Pull request merged**
