### PR TITLE
Run CI for tuf-test-vector

### PR DESCRIPTION
**Pull request by xcheng-here**
Signed-off-by: cheng.xiang <ext-cheng.xiang@here.com>

### CODE REVIEW

**Comment by patrickvacek** [comment]
Why wasn't gitlab's CI automatically triggered?

**Comment by patrickvacek** [comment]
gitlab is complaining with "Invalid reference name: fix/OTA-2149/large_meta/run_ci" while trying to sync with gihub. Not quite sure why but we don't normally have 3 slashes. I wonder if that's connected somehow? Can you try removing the `/run_ci` part?

**Comment by patrickvacek** [comment]
Now I see, it's because there's already a branch named `fix/OTA-2149/large_meta`. I've started a CI run on that branch: https://main.gitlab.in.here.com/olp/edge/ota/connect/client/aktualizr/pipelines/545039

**Comment by patrickvacek** [comment]
I've merged https://github.com/advancedtelematic/tuf-test-vectors/pull/70 so this can get updated as well.

**Comment by lbonn** [comment]
Updated to use the new master tip.

**Comment by patrickvacek** [comment]
CI might still be failing because of the branch name problem.

**Comment by patrickvacek** [comment]
Removed the offending branch in gitlab and now CI is running.

**Pull request merged**
