### PR TITLE
Test/pro 4700/ostree creds

### PR DESCRIPTION
**Pull request by patrickvacek**
Mostly testing and fixing up holes.

### CODE REVIEW

**Comment by patrickvacek** [comment]
I like how I added 8 new unit tests and barely touched "actual" code yet somehow coverage went down by .01%.

**Comment by patrickvacek** [comment]
P11 changes will make the tests fail, do not merge yet.

**Comment by patrickvacek** [comment]
Rebased and ready.

**Comment by cajun-rat** [comment]
Nice!

**Pull request merged**
