### PR TITLE
Minor fixes to make clang-tidy-7 happy

### PR DESCRIPTION
**Pull request by eu-smirnov**
Signed-off-by: Eugene Smirnov <evgenii.smirnov@here.com>

### CODE REVIEW

**Comment by eu-smirnov** [comment]
@patrickvacek Clang 6.0.1 on Travis and Jenkins and no clang at all on Gitlab.

**Comment by eu-smirnov** [comment]
BTW, clang 8.0 was released two days ago, so we might want to skip 7 and jump straight to 8.

**Comment by lbonn** [comment]
> no clang at all on Gitlab.

:cry:

**Comment by patrickvacek** [comment]
No clang is sad clang. But I'm also in favor jumping to 8 if all our environments support it. And by "all our environments" I think I just mean Debian stable and Ubuntu 16.04/18.04.

**Comment by eu-smirnov** [comment]
@lbonn Right, sorry, I looked to the wrong job, clang 6.0.1 on Gitlab as well

**Pull request merged**
