### PR TITLE
Do not try to unpack boostrap credentials when no-root is specified

### PR DESCRIPTION
**Pull request by OYTIS**
Required to support _real_ implicit provisioning

### CODE REVIEW

**Comment by cajun-rat** [comment]
Shall we sit down tomorrow and work through how this should work?

**Comment by OYTIS** [comment]
@patrickvacek @cajun-rat 
We've agreed with @jerrytrieu on credentials.zip format that contains everything that 'normal' credentials.zip has except autoprov.p12. `Bootstrap::readServerUrl` just needs autoprov.url, which is there for implicit provisioning, but `Bootstrap::Bootstrap()` looks for autoprov.p12 qute naturally and crashes.

**Comment by patrickvacek** [comment]
Yes, I'm all too familiar with that crash! We should consider some refactoring to make it actually work correctly.

**Comment by OYTIS** [comment]
@patrickvacek Oops, you're right, it crashes anyway. Let's discuss that tomorrow.

**Comment by OYTIS** [comment]
@patrickvacek Oh no, it works, I just forgot to add `--no-root-ca` to the command line. I will use this branch to test Spekulatius for now and we can come up with something better tomorrow.

**Comment by patrickvacek** [comment]
@OYTIS Right you are. Still seems like a problem for the case without `--no-root-ca` though. Didn't we want to be able to push new root CAs as part of the image?

**Comment by patrickvacek** [comment]
@OYTIS I made a small change that makes things a bit cleaner. I thought this ought to work smoothly for all cases.

**Pull request merged**
