### PR TITLE
Resurrect provisioning and check for updates load tests

### PR DESCRIPTION
**Pull request by koshelev**

### CODE REVIEW

**Comment by patrickvacek** [comment]
Looks like formatting complaints. Code seems fine at first glance.

**Comment by patrickvacek** [comment]
`rebase HEAD~2 --signoff`?

**Comment by lbonn** [comment]
Hm sorry formatting is still off, it needs to be done with clang-format-6.0. When installed, it will be picked up by CMake (will need a reconfigure). It's available on current Ubuntu/Debian versions from apt.

**Comment by patrickvacek** [comment]
@koshelev Would it be helpful if me or someone else did a quick fix of the formatting issues here? I don't want to keep holding this up just because of minor issues.

**Comment by koshelev** [comment]
Seems like I used a wrong version of formatter. Will try again

**Pull request merged**
