### PR TITLE
Fix veracode packing

### PR DESCRIPTION
**Pull request by zabbal**
Properly add binaries to the veracode submission archieve.

### CODE REVIEW

**Comment by lbonn** [comment]
Apparently, some other issues need to be fixed. Holding that off for now.

**Comment by zabbal** [comment]
Ok, we can go ahead with merging. Corresponding schedule is temporary disabled - will be re-enabled once SPC clarify issue with compiler support with veracode.

**Comment by patrickvacek** [comment]
> Ok, we can go ahead with merging.

We need to address the CI failure before we can merge. Does it just need to be an "allow failure" type of thing?

**Comment by zabbal** [comment]
The CI failure is the reason I've disabled the schedule: right now the 1st submission succeed, 2nd fail due to problem on veracode side. So yes, I think it should be "allow failure" - at least until veracode is fixed and stable enough. I think I saw patch from @lbonn which allows this to fail.

**Comment by lbonn** [comment]
Ok, here is it with `allow_failure`

**Comment by zabbal** [comment]
Seems like I'm not authorized to merge this. @patrickvacek - feel free to if it looks fine.

**Pull request merged**
