### PR TITLE
OTA-3746: Adding github-only note

### PR DESCRIPTION
**Pull request by merltron**
Adding note to all topics that directs people to the rendered version of the article in the docs portal.

We discussed this during our versioning meeting. For more details, see the meeting notes: https://confluence.in.here.com/display/OTA/MEETING+MINUTES%3A+Docs+versioning

Signed-off-by: Merlin Carter <merlin.carter@here.com>

### CODE REVIEW

**Comment by merltron** [comment]
> I'm not sure I like the approach of defining a branch with an attribute. That would imply that we would change it for each `version-docs` branch, which would be one extra make-work task for the docs release process. I don't think we lose much by always linking to `latest`.

OK, noporobs - will make it always point to latest

**Comment by merltron** [comment]
@tkfu OK removed branch attr as requested - have another look.

**Comment by tkfu** [comment]
I'd suggest using a squash merge, since the 2nd commit just undoes all the same stuff.

**Comment by merltron** [comment]
@tkfu OK, I squashed the other commit - I can't merge until I get an approve.

**Comment by tkfu** [comment]
Oops, sorry, thought I had approved with that comment. Squash merge is one of the options in the dropdown menu you get from the arrow next to the merge button on github, but the way you did it is also just fine.

**Pull request merged**
