### PR TITLE
Feat/ota 617/fix 18.04 ci

### PR DESCRIPTION
**Pull request by lbonn**
~work in progress~

### CODE REVIEW

**Comment by patrickvacek** [comment]
Still WIP, or is this ready?

**Comment by lbonn** [comment]
These could be merged but I'd like to push some other changes in p11engine.cc when I'm done.

**Comment by patrickvacek** [comment]
It can wait until you're happy. No rush, sorry!

**Comment by patrickvacek** [comment]
Wow that's a lot of suppressions!

**Comment by lbonn** [comment]
Yes, let's remove some to keep the balance :).

The last resisting ostree leak should now appear on CI for 16.04.

**Comment by lbonn** [comment]
Ok, it should be fine soon when I would have squashed all these annoying CI formalities.

There is a lot of different things but the only controversial commit is probably "Manually generate RSA key then store it on the HSM".

Spin-off PRs:
https://github.com/OpenSC/libp11/pull/246
https://github.com/ostreedev/ostree/pull/1716

**Comment by lbonn** [comment]
@patrickvacek We have an [hardcoded .deb file in the repository](https://github.com/advancedtelematic/aktualizr/blob/c1fdabfdcd794bd068ef9bdc39d0e49b4df1afb6/tests/test_data/fake_root/repo/repo/targets/selfupdate_2.0) which was built for 16.04 and does not install on 18.04.

Making the test work for both versions is a bit painful and I judged it out of scope for this PR.

**Comment by patrickvacek** [comment]
> We have an hardcoded .deb file in the repository which was built for 16.04 and does not install on 18.04.

Ah jeez, yeah, that's a task for another day.

**Pull request merged**
